### PR TITLE
Apply outerMargin to non-fluid grids as well

### LINKED ISSUE #19: Why is gutter dependent on fluid setting?
I want to use a gutter in the normal grid setting (specified width), but I see in the code that `fluid` is required to use a gutter. I wonder why that is?

### LINKED ISSUE #118: "outerMargin" not applied when the grid is NOT fluid
The "outerMargin" property is translated as padding for the Grid component.
But this seems to be applied only when the Grid is fluid.

"react-styled-flexboxgrid": "^2.2.0",
"styled-components": "^3.2.3",

### PR DESCRIPTION
**Pull request by misund**
Fixes #19 
Fixes #118

### CODE REVIEW

**Comment by misund** [comment]
I see that tests fail on node 7. However, the same goes for the master branch.

**Comment by LoicMahieu** [comment]
Hi @misund 
Thanks for your contribution!

I really don't know if your modification could break something. In fact I don't use theses components directly but my work team mates does ;) I asked them to come check the issues and give their feedbacks.

You seems confortable with this project. Do you think it deserve the general interest ?
Also, are you interested to become a contributor of this project ?

**Comment by misund** [comment]
> Do you think it deserve the general interest ?
You'll have to forgive that English is not my first language, I'm having some trouble understanding this question. Are you asking if I think that the project is deserving of the interest it receives from others?

For my own part, what sparked my interest was our company's current process to move from Foundation-based styleguides to a storybook one. In starting that, I was looking for a grid system in styled-components that had a UI resembling what our designers was already used to. So far, the grid's been doing what it's supposed to (with the exception of this particular outerMargin issue, that we've solved). In that regard, I guess you could say the system deserves some attention.

> Also, are you interested to become a contributor of this project ?
What would you expect of a contributor?

**Comment by heff** [comment]
@misund thanks!! This saved me.

👍 on merging this in.

| Without PR  | With PR  |
|--|--|
|screen shot 2018-02-16 at 2 32 20 pm|screen shot 2018-02-16 at 2 33 34 pm|

### My theme settings

```javascript
const theme = {
  flexboxgrid: {
    // Defaults
    gridSize: 12, // Rem
    gutterWidth: 1, // Rem
    outerMargin: 1, // Rem
    mediaQuery: `only screen`,
    container: {
      // Xs: 20,
      sm: 46, // Rem
      md: 61, // Rem
      lg: 71 // Rem
    },
    breakpoints: {
      xs: 0, // Em
      sm: 48, // Em
      md: 64, // Em
      lg: 75 // Em
    }
  }
}
```

**Comment by heff** [comment]
Also, thanks for the grid @LoicMahieu! It's been great to work with.

**Comment by davereid91** [comment]
@LoicMahieu Is there any chance you could merge this in? Thanks

**Comment by LoicMahieu** [comment]
Hey folks!

Sorry to be sooooo late! I was busy with others stuffs and I didn't have at least one minute for this project. Thanks for your patience ;)

Thanks @misund for your contribution, again! 👍

Originally this project was completely inspired by [`flexboxgrid.css`](https://github.com/kristoferjoseph/flexboxgrid) and this base idea was to follow strictly its behavior.
But with time, I understand that we could (should?) derivate to our own destiny 😄

In `flexboxgrid.css`, the `.container` does [not have paddings](https://github.com/kristoferjoseph/flexboxgrid/blob/master/src/css/flexboxgrid.css#L23-L31) and have a [`width`](https://github.com/kristoferjoseph/flexboxgrid/blob/master/src/css/flexboxgrid.css#L241-L243).

But anyway I agree that gutter should not be especially depends on `fluid` and can be applied to a "fixed width" grid. I digged in our app codebase where we used this package and it seems that non-fluid Grid are never used. I am not a frontend designer so I don't really know what is the best thing to do.
As there are people who are requesting this functionality, I am ok with it.

1. Should we make this the default behavior and introduce a breaking change. Add a new prop, `noGutter` for example, to go back to the current behavior ?
2. Make this behavior under a new prop, `withGutter` for example ?

What would you prefer ?

**Comment by misund** [comment]
I don't think that we'd need the `noGutter` prop, because the same effect can be achieved by setting outerMargin to 0.

**Comment by LoicMahieu** [comment]
Enough for me! Let's merge it! Thanks!

**Comment by LoicMahieu** [comment]
v2.4.0

**Pull request merged**
